name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Copy code to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@3.92.215.237 "rm -rf /home/ubuntu/app && mkdir -p /home/ubuntu/app"
        rsync -avz --exclude='.git' ./ ubuntu@3.92.215.237:/home/ubuntu/app

    - name: Install Docker on EC2 and Add Permissions
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@3.92.215.237 << 'EOF'
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo usermod -aG docker ubuntu
          sudo systemctl enable docker
          sudo systemctl start docker
        EOF

    - name: Deploy on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@3.92.215.237 << 'EOF'
          cd /home/ubuntu/app
          docker stop flask-app || true
          docker rm flask-app || true
          docker build -t flask-app .
          docker run -d -p 80:5000 --name flask-app flask-app
        EOF
